language: php
sudo: false

php:
  - '7.0'
  - hhvm
  - nightly

before_script:
    - cp app/config/parameters.yml.dist app/config/parameters.yml
    - mkdir -p build/logs
    - echo $COVERALLS_APIKEY > .coveralls.yml
    - composer self-update
    - composer install
    - php bin/console doctrine:database:create
    - php bin/console doctrine:schema:create
    - php bin/console doctrine:fixtures:load -n
    - composer require satooshi/php-coveralls

matrix:
  allow_failures:
    - php: nightly
  fast_finish: true

script:
    - vendor/bin/phpunit src/Library/

cache:
    composer: true
directories: vendor

after_success:
    - travis_retry php vendor/bin/coveralls -v