language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

addons:
  apt:
    packages:
      - parallel

php:
  - 7.0
  - hhvm
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

before_script:
    - rm -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
    - flags="--prefer-dist"
    - composer install $flags
    - bin/composer install $flags
    - git config --global user.name travis-ci
    - git config --global user.email travis@example.com

