language: php
sudo: false

services:
  - mysql

cache:
  directories:
    - $HOME/.composer/cache

addons:
  apt:
    packages:
      - parallel

php:
  - 7.0
  - 7.1
  - hhvm
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

env:
  - SYMFONY_VERSION="3.0.*" DB=mysql

before_script:
    - rm -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
    - mkdir vendor
    - composer install

before-install:
  - composer self-update

install:
  - cp app/config/parameters.yml.dist app/config/parameters.yml

script:
  - mkdir -p build/logs
  - phpunit --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v

notifications:
slack: nonio:Qw2vMbsIGDOVdWScx3hazBzA